### ISSUE TITLE
icon_resources not documented

### ISSUE THREAD

**Issue by urishab** [py2exe/py2exe#153] opened 2022-10-04 13:53 UTC
going over the new documentation I don't see any reference to icon_resources that was used to assign an icon to an executable.
Not sure if this is by design or not.

In the old interface the windows= and the console= didn't just accept a list of string.
You could give a list of dictionaries with the following options:
"script": the name of the python file to freeze,
"version": this was used for version information in the bundle
"dest_base": the name of the executable if different than the source python file,
"icon_resources": list of tuples of icons to include, each is icon number and filename,

**Comment by urishab** [comment] 2022-10-04 13:58
I see the interface still works when using freeze (except for version=)
Seems to me important to keep the interface around as well as document it

**Comment by Athanasius** [comment] 2022-10-04 14:03
> also, the type definitions in the library do not allow dict as values for windows=, etc. Although it is accepted and runs as expected

I noted this in https://github.com/py2exe/py2exe/issues/152

**Comment by albertosottile** [comment] 2022-10-04 17:32
Thanks for reporting this. Closing as duplicate of #152.

**Closed by albertosottile** 2022-10-04 17:32 UTC
