### ISSUE TITLE
Inconsistent builds: ExtensionDLL copying order

### ISSUE THREAD

**Issue by lordkekz** [py2exe/py2exe#149] opened 2022-09-07 18:02 UTC
I just found an issue that seems very similar to issue #96 
I'm going to provide an example and try to point out what is different from #96 

My setup.py looks like this:
```
from distutils.core import setup
import py2exe, sys

# Insert argument so I don't have to write it in the command line
if "py2exe" not in sys.argv:
    sys.argv.append("py2exe")

setup(
    options = {'py2exe': {'bundle_files': 3}},
    zipfile = None,
    console = [{
            "script":"demonstration.py",
            "dest_base":"demonstration"
            }]
)
```

And I have a demonstration.py like so:
```
import wmi
import pystray

# actual app uses pystray for an icon in the system tray

# test WMI
c = wmi.WMI()
for display in c.Win32_DesktopMonitor():
    print(f"Monitor '{display.Name}' got PNPDeviceID:", display.PNPDeviceID)
```

### Build outputs (full outputs in attachments)
Working build output:
```
[...]
Copy ExtensionDLL C:\Users\LordKekz\anaconda3\envs\NetDisplay\lib\site-packages\pywin32_system32\pywintypes39.dll to dist
Copy ExtensionDLL C:\Users\LordKekz\anaconda3\Library\bin\pythoncom39.dll to dist
Copy ExtensionDLL C:\Users\LordKekz\anaconda3\envs\NetDisplay\lib\site-packages\pywin32_system32\pythoncom39.dll to dist
```
Broken build output:
```
[...]
Copy ExtensionDLL C:\Users\LordKekz\anaconda3\envs\NetDisplay\lib\site-packages\pywin32_system32\pythoncom39.dll to dist
Copy ExtensionDLL C:\Users\LordKekz\anaconda3\envs\NetDisplay\lib\site-packages\pywin32_system32\pywintypes39.dll to dist
Copy ExtensionDLL C:\Users\LordKekz\anaconda3\Library\bin\pythoncom39.dll to dist
```

### Program outputs
Working builds print some info about connected monitors:
```
Monitor 'Nicht-PnP Monitor (Standard)' got PNPDeviceID: DISPLAY\DEFAULT_MONITOR\1&28A6823A&0&UID256
Monitor 'Standardmonitor' got PNPDeviceID: None
Monitor 'Surface Display' got PNPDeviceID: DISPLAY\LGD0554\4&1AAA636&0&UID265988
```
Broken builds crash because of a missing procedure in the conflicting DLL:
```
Traceback (most recent call last):
  File "demonstration.py", line 1, in <module>
    import wmi
  File "<frozen zipimport>", line 259, in load_module
  File "wmi.pyc", line 105, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "win32com\__init__.pyc", line 6, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "pythoncom.pyc", line 4, in <module>
  File "pywintypes.pyc", line 118, in __import_pywin32_system_module__
ImportError: DLL load failed while importing pythoncom: Die angegebene Prozedur wurde nicht gefunden.
```

### Differences from #96
1. I'm using bundle_files=3; #96 was using bundle_files=1
2. The conflicting DLL is an ExtensionDLL; in #96 it only said DLL
3. The DLL conflict occurs specifically between the WMI and pystray packages, since they seem to depend on different versions of the same DLL. Each package builds fine consistently on its own.
I'm not sure if py2exe has any way of deciding which DLL to use, since they might just both be valid dependencies. In that case it would be nice to be able to define a preference in setup.py

### Behavior with bundle_files=1
I tried the same example, except using bundle_files=1. In that case, there was a hint about the conflict in the build output:
```
[...]
? yacctab                             imported from pycparser._build_tables
Building 'dist\demonstration.exe'.
C:\Users\LordKekz\anaconda3\envs\NetDisplay\lib\zipfile.py:1514: UserWarning: Duplicate name: 'pythoncom39.dll'
  return self._open_to_write(zinfo, force_zip64=force_zip64)
Copy DLL C:\Users\LordKekz\anaconda3\envs\NetDisplay\Library\bin\libssl-3-x64.dll to dist
Copy DLL C:\Users\LordKekz\anaconda3\envs\NetDisplay\MSVCP140.dll to dist
[...]
```
py2exe then always puts both of the DLLs into the executable: (the newer one is from the WMI dependency pywin32; that's the only one I want)
![grafik](https://user-images.githubusercontent.com/50516935/188943340-5d760b4b-b1a5-44a7-b603-d4ae84f64fb4.png)
but still the program crashes at runtime: (I don't know if it's due to the conflict though)
```
Traceback (most recent call last):
  File "demonstration.py", line 1, in <module>
    import wmi
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "zipextimporter.pyc", line 97, in load_module
  File "<frozen zipimport>", line 259, in load_module
  File "wmi.pyc", line 105, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "zipextimporter.pyc", line 97, in load_module
  File "<frozen zipimport>", line 259, in load_module
  File "win32com\__init__.pyc", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "zipextimporter.pyc", line 97, in load_module
  File "<frozen zipimport>", line 259, in load_module
  File "pythoncom.pyc", line 4, in <module>

AttributeError: module 'pywintypes' has no attribute '__import_pywin32_system_module__'
```

Note that pystray alone also generates the duplicate warning and both DLLs are in the executable. pystray works anyways. Only WMI fails once it encounters the duplicate/wrong version DLL. You can test pystray by changing demonstration.py:
```
import pystray
import PIL.Image as Image

image=Image.open("icon.ico")
trayicon=pystray.Icon(name="demonstration_trayicon", icon=image, title="Demonstration")
trayicon.menu = [pystray.MenuItem('Quit', trayicon.stop)]
trayicon.run()
```

### Attachments
[build_broken_bundle_files.txt](https://github.com/py2exe/py2exe/files/9508571/build_broken_bundle_files.txt)
[build_working.txt](https://github.com/py2exe/py2exe/files/9508572/build_working.txt)
[build_broken.txt](https://github.com/py2exe/py2exe/files/9508573/build_broken.txt)

**Comment by albertosottile** [comment] 2022-09-19 07:05
Hello, thanks for having reporting this. I understand your issue, in principle, but I am not convinced about the diagnosis in this particular case. 

I tried to reproduce your issue in an isolated environment (a Windows Docker container) and I was not able to reproduce. To the best of my knowledge, `pystray` does NOT depend on `pywin32` and so has no reason to require a `pythoncom39.dll` library. Indeed, if you look at the dependency chain of `pystray`, or if you install it on its own in an isolated environment, this library is not installed at all. I also confirmed this by freezing your second, `pystray`-only, example and verifying it works without the aforementioned DLL.

Therefore, your issue is that `py2exe` is sometimes picking the wrong DLL when freezing WMI. First, I would like to clarify that freezing from `conda` and `virtualenv` is not actively supported, as these have significant influence on the environment, as confirmed by this issue. I would hence advise you to use Docker or a clean Python installation, if possible. 

Second, it seems to me that the `conda` environment is responsible for providing a "rogue" copy of `pythoncom39.dll`. `py2exe` looks for compatible libraries in your `PATH`. Thus, to solve your particular issue here, I would just remove the folder `C:\Users\LordKekz\anaconda3\Library\bin\` from your `PATH` right before freezing your app. 

Third, w.r.t. this statement

> I'm not sure if py2exe has any way of deciding which DLL to use, since they might just both be valid dependencies. In that case it would be nice to be able to define a preference in setup.py

At the moment `py2exe` does not provide such a mechanism for libraries with the same file name. There is a `dll_excludes` option, but it only accepts DLL file names, and so will exclude both files, in your case. 

In principle, I understand the rationale behind this proposal, but I am not convinced this would be the right way to go. I honestly see no difference between what `py2exe` is doing and what Python would do when running the code: trying to pick the right library to link against. 

Because both libraries can apparently be linked to the cPython code (we run `BindImageEx` on the target DLLs before bundling them when freezing), I suspect this issue can very well occur at runtime in an environment like yours. Therefore, I would rather act on the environment (avoid using `conda` or restrict `PATH` before freezing) than add a quite complicated feature to `py2exe`.

I hope this helps. Please report here if you still have the same issue after applying the suggestions mentioned before.

**Comment by albertosottile** [comment] 2022-10-12 15:22
Closing this as no further input was provided.

**Closed by albertosottile** 2022-10-12 15:22 UTC
Labels: requires user input, unable to reproduce
