### ISSUE TITLE
Using certifi as a dependency isn't supported when --bundle-files=0

### ISSUE THREAD

**Issue by gamer191** [py2exe/py2exe#133] opened 2022-05-13 12:12 UTC
This can be tested by running `setup.py py2exe && dist\certifi_test.exe` on https://github.com/pukkandan/certifi_test, which results in this output:
```
running py2exe

  12 missing Modules
  ------------------
? _frozen_importlib                   imported from importlib, importlib.abc, zipimport
? _frozen_importlib_external          imported from importlib, importlib._bootstrap, importlib.abc, zipimport
? _posixshmem                         imported from multiprocessing.resource_tracker, multiprocessing.shared_memory
? _winreg                             imported from platform
? asyncio.DefaultEventLoopPolicy      imported from -
? dummy.Process                       imported from multiprocessing.pool
? java.lang                           imported from platform
? org.python.core                     imported from copy, pickle
? os.path                             imported from ctypes._aix, distutils.file_util, os, pkgutil, py_compile, sysconfig, tracemalloc, unittest, unittest.util
? pep517                              imported from importlib.metadata
? readline                            imported from cmd, code, pdb
? resource                            imported from test.support
Building 'dist\certifi_test.exe'.
D:\TRASH\certifi_test\dist\cacert.pem
Traceback (most recent call last):
  File "__main__.py", line 8, in <module>
    context.load_verify_locations(cafile=certifi.where())
FileNotFoundError: [Errno 2] No such file or directory
```

The reason this happens is because Certifi has to load an external file, cacert.pem (which, by the way, can be downloaded from https://raw.githubusercontent.com/certifi/python-certifi/master/certifi/cacert.pem), but bundle-files=0's purpose is obviously not to use any external files. I'm not able to test this right now, but I'm guessing that the command above would succeed if there was an existing dist\cacert.pem file in the repo. [This program](https://github.com/yt-dlp/yt-dlp/releases/tag/2022.04.08) (make sure to use yt-dlp_min.exe, as the other builds aren't built using py2exe), for example, only executes successfully (and returns an error, because you haven't used any URLs with it), if certifi.pem is available in the same directory as it.

PS: I did not make the certifi_test repo, thanks Pukkandan

**Comment by gamer191** [comment] 2022-05-13 12:31
PS: the reason this happens is because Certifi has to load an external file, cacert.pem (which, by the way, can be downloaded from https://raw.githubusercontent.com/certifi/python-certifi/master/certifi/cacert.pem), but bundle-files=0's purpose is obviously not to use any external files. I'm not able to test this right now, but I'm guessing that the command above would succeed if there was an existing dist\cacert.pem file in the repo. [This program](https://github.com/yt-dlp/yt-dlp/releases/tag/2022.04.08) (make sure to use yt-dlp_min.exe, the other builds aren't built using py2exe), for example, only executes successfully (and returns an error, because you haven't used any URLs with it), if certifi.pem is available in the same directory as it.

PS: I did not make the certifi_test repo, thanks Pukkandan

**Comment by albertosottile** [comment] 2022-05-22 12:47
This is expected behavior. As you correctly pointed out, `certifi` requires an external .pem file to function. As a general limitation, `bundle_files <= 2` is currently supported only for standard library packages, as I do not have the capacity to maintain compatibility with all the Python ecosystem. Hence, II do not have plans for fixing this issue. Perhaps I could add a minimum supported value of `bundle_files` for `certifi` in the next release, to make this failure explicit.

On the other hand, if you wish to have support for this package and this level of bundling, a PR that implements the necessary features is more than welcome. 

Nevertheless, at the moment I am closing this issue for the reason mentioned above.

**Closed by albertosottile** 2022-05-22 12:47 UTC

**Comment by gamer191** [comment] 2022-05-23 12:53
> As a general limitation, `bundle_files <= 2` is currently supported only for standard library packages, as I do not have the capacity to maintain compatibility with all the Python ecosystem. Hence, II do not have plans for fixing this issue

Fair enough



> Perhaps I could add a minimum supported value of `bundle_files` for `certifi` in the next release, to make this failure explicit

Would force some py2exe users to separately distribute more files than just certifi.pem? If yes, is it possible to make it a warning only?

> On the other hand, if you wish to have support for this package and this level of bundling, a PR that implements the necessary features is more than welcome.

I don't know this program anywhere near well enough to. Maybe one day😂
