### ISSUE TITLE
simple "hello world" failing due to Windows restrictions

### ISSUE THREAD

**Issue by rlodbrok** [py2exe/py2exe#76] opened 2021-03-12 21:36 UTC
My corporate laptop does not allow me to write in C:\Program Files\WindowsApps\Python*
Can i compile and avoid writing in this location?

hello.py
```
print("Hello World")
```

setup.py
```
from distutils.core import setup
import py2exe
setup(console=['hello.py'])
```

output (using py2exe v0.10.2.1)
```
C:\_mydata\Development\Py_test1>python setup.py install
running install
running build
running install_egg_info
Writing C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\Lib\site-packages\UNKNOWN-0.0.0-py3.9.egg-info
error: [Errno 13] Permission denied: 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\\Lib\\site-packages\\UNKNOWN-0.0.0-py3.9.egg-info'
```
ATTENTION: i get exactly the same in a admin cmd line (I cannot change the windows permissions due to policy)!

Desparately i tried the following, which offcourse gives me new problems.
```
C:\_mydata\Development\Py_test1>python -m py2exe.build_exe hello.py
  3 missing Modules
  ------------------
? _posixshmem                         imported from multiprocessing.resource_tracker, multiprocessing.shared_memory
? readline                            imported from cmd, code, pdb
? test.support                        imported from multiprocessing.util
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\XYZ\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\py2exe\build_exe.py", line 141, in <module>
    main()
  File "C:\Users\XYZ\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\py2exe\build_exe.py", line 138, in main
    builder.build()
  File "C:\Users\XYZ\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\py2exe\runtime.py", line 238, in build
    self.build_exe(target, exe_path, options.libname)
AttributeError: 'Namespace' object has no attribute 'libname'

```

**Comment by Athanasius** [comment] 2021-03-12 21:40
Try `python setup.py py2exe` instead.  Should build in current directory.  The issue is likely you using the 'install' target, as it does then indeed want to go straight to installing the built package.

**Comment by albertosottile** [comment] 2021-03-13 14:25
Hi, thanks for reporting this.

As suggested by @Athanasius, your command tries to install your package in your system Python environment, triggering your permission issue. 

If you want to build a packed executable from your code, you should run `python setup.py py2exe`.

**Comment by rlodbrok** [comment] 2021-03-13 19:29
Thank you for the response, i still get the below error.
```
C:\_mydata\Development\Py_test1>python setup.py py2exe
running py2exe

  3 missing Modules
  ------------------
? _posixshmem                         imported from multiprocessing.resource_tracker, multiprocessing.shared_memory
? readline                            imported from cmd, code, pdb
? test.support                        imported from multiprocessing.util
Building 'dist\hello.exe'.
error: [WinError 87] The parameter is incorrect.
```

pip install readline
```
C:\_mydata\Development\Py_test1>pip install readline
Collecting readline
  Using cached readline-6.2.4.1.tar.gz (2.3 MB)
    ERROR: Command errored out with exit status 1:
...
    Complete output (1 lines):
    error: this module is not meant to work on Windows
...
============ Building the readline library ============
    The system cannot find the path specified.
```

**Comment by albertosottile** [comment] 2021-03-14 10:00
The missing `readline` module is expected behavior, as this module is not required on Windows. I would uninstall `pyreadline` to avoid further polluting the environment.

It is hard to help you as it is basically impossible for me to reproduce your issue, since it is unique to your system. 

One thing that you could do is to build the executable with a higher verbose flag. Could you edit your `setup.py` as it follows:
```python
from distutils.core import setup
import py2exe

setup(console=[{"script": "hello.py"}],
      options={"py2exe": {
               "verbose": 4}
              },
     )

```

try again to build via `python setup.py py2exe` and report here the logs?

Also, a little more information on your environment could help. Could you report here the output of the following commands?
```
python --version
python -m platform
python -m site
```

**Comment by leejeonghun** [comment] 2021-03-15 06:22
> Writing C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\Lib\site-packages\UNKNOWN-0.0.0-py3.9.egg-info

It seems you using Python from Window Store. I'd like to suggest you using Win32 version instead of Store version. You can download the latest version here: https://www.python.org/downloads/release/python-392/

**Comment by rlodbrok** [comment] 2021-03-15 11:24
i have removed the Microsoft store version and installed the win32 version as advised. 
The problem remains the problematic.
Something did change: error 87 is now 110.

Running with adjusted setup.py to include verbose 4 level...
```
C:\_mydata\Development\Py_test1>python setup.py py2exe
running py2exe

  3 missing Modules
  ------------------
? _posixshmem                         imported from multiprocessing.resource_tracker, multiprocessing.shared_memory
? readline                            imported from cmd, code, pdb
? resource                            imported from test.support
Building 'dist\hello.exe'.
Add resource PYTHONSCRIPT/1(2393 bytes) to dist\hello.exe
error: [WinError 110] The system cannot open the device or file specified.
```
_PS: No files or terminals are locking any files to my knowledge. I even did a reboot and opened a single cmd to run the build._

Running the generated hello.exe
```
C:\_mydata\Development\Py_test1\dist>hello.exe
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'C:\_mydata\Development\Py_test1\dist\hello.exe'
  isolated = 1
  environment = 0
  user site = 0
  import site = 0
  sys._base_executable = 'C:\\_mydata\\Development\\Py_test1\\dist\\hello.exe'
  sys.base_prefix = ''
  sys.base_exec_prefix = ''
  sys.platlibdir = 'lib'
  sys.executable = 'C:\\_mydata\\Development\\Py_test1\\dist\\hello.exe'
  sys.prefix = ''
  sys.exec_prefix = ''
  sys.path = [
    'C:\\_mydata\\Development\\Py_test1\\dist\\library.zip',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00004be4 (most recent call first):
<no Python frame>
```

Setup details
```
C:\_mydata\Development\Py_test1\dist>python --version
Python 3.9.2

C:\_mydata\Development\Py_test1\dist>python -m platform
Windows-10-10.0.19041-SP0

C:\_mydata\Development\Py_test1\dist>python -m site
sys.path = [
    'C:\\_mydata\\Development\\Py_test1\\dist',
    'C:\\Users\\XYZ\\AppData\\Local\\Programs\\Python\\Python39-32\\python39.zip',
    'C:\\Users\\XYZ\\AppData\\Local\\Programs\\Python\\Python39-32\\DLLs',
    'C:\\Users\\XYZ\\AppData\\Local\\Programs\\Python\\Python39-32\\lib',
    'C:\\Users\\XYZ\\AppData\\Local\\Programs\\Python\\Python39-32',
    'C:\\Users\\XYZ\\AppData\\Local\\Programs\\Python\\Python39-32\\lib\\site-packages',
]
USER_BASE: 'C:\\Users\\XYZ\\AppData\\Roaming\\Python' (doesn't exist)
USER_SITE: 'C:\\Users\\XYZ\\AppData\\Roaming\\Python\\Python39\\site-packages' (doesn't exist)
ENABLE_USER_SITE: True
```

**Comment by albertosottile** [comment] 2021-03-16 22:12
To build the packed executable, `py2exe` uses `kernel32` API, specifically https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-updateresourcew, to add resources in the executable (including the main Python script, which is the line in which your build crashes). 

I would say the exception you are seeing is raised by https://github.com/py2exe/py2exe/blob/b8b9cf60d1ac3f243e09330b29a6bc7de419929b/py2exe/resources.py#L33-L49

What does that mean, though? Again, without knowing what is unique in your system, this is just guessing, but I would say either:
- the Win32 `UpdateResourceW` API cannot access the `hello.exe` file under building (perhaps because some other program is accessing that, e.g. a backup system/a monitor that checks executables/an antivirus/you name it)
- the kernel32 DLL cannot be correctly loaded by `ctypes` and so `py2exe` is not even able to run `UpdateResourceW` at all (incidentally, what is your Windows version?). I do not know if access to this API might be limited by OS policies but this might also be the case.

I am afraid this does not really help you in solving your issue. Once again, I would encourage you to build from a clean environment (e.g. a VM or a Windows Docker container).

**Comment by albertosottile** [comment] 2021-03-28 13:14
Closing this as it is not related to the codebase but rather to the specific environment. Feel free to open another issue if you experience further problems with `py2exe`.

**Closed by albertosottile** 2021-03-28 13:14 UTC
Labels: invalid
