### ISSUE TITLE
Link on the py2exe wiki page does not go anywhere

### ISSUE THREAD

**Issue by ThomasEwaldETH** [py2exe/py2exe#183] opened 2023-04-28 14:55 UTC
Hello there!
First, thanks for the great program!
I just noticed a minor detail: The link on the py2exe [wiki page (installation)](https://pypi.org/project/py2exe/), which says "Use the py2exe.freeze function as documented [here](https://pypi.org/project/py2exe/docs/py2exe.freeze.md)." does not lead anywhere.
Best regards and have a nice day!
Thomas

**Comment by albertosottile** [comment] 2023-05-12 17:25
Thank you for this issue, This is patched in the `develop` branch and will be fixed in the next release.

**Comment by albertosottile** [comment] 2023-05-12 17:27
Closing this as duplicate of #162.

**Closed by albertosottile** 2023-05-12 17:27 UTC
Labels: documentation
