### ISSUE TITLE
Include site module?

### ISSUE THREAD

**Issue by mharbison72** [py2exe/py2exe#154] opened 2022-10-10 16:51 UTC
I see that the `site` module is excluded from the builds in `hooks.py`, and `Py_NoSiteFlag` and `Py_NoUserSiteDirectory` are set when initializing the interpreter.  These lines predate the import into github, so I'm wondering if you have any insight into why this is the case (or if not, objections to including it).  I suppose it makes some sense if the goal is to completely isolate the app from any python installed on the system, but with TortoioseHg, I'd like to be able to pip-install extensions to the user site directory and have that visible to the app.  Additionally, importing `site` adds several things to `__builtins__`[1], which means Mercurial behaves slightly differently in some cases, depending on if it's built with py2exe or a different method.  Opting into `Py_NoSiteFlag` and `Py_NoUserSiteDirectory` as a build time option seems fine, if you have compatibility concerns in the default case.

[1] https://docs.python.org/3/library/constants.html#constants-added-by-the-site-module

**Comment by albertosottile** [comment] 2022-10-12 15:21
IMHO, the purpose of the `site` module is to configure a `USER_SITE` that the user can employ to install packages in their Python distribution. Since the distribution embedded in the bundles generated by `py2exe` does not support this (we would have to ship a full `py2exe` runtime in each app), I do not see the value of including `site` in the app bundles.

> I suppose it makes some sense if the goal is to completely isolate the app from any python installed on the system,

That is indeed part of the goal. Apps packed with `py2exe` include their own Python interpreter and `site-packages`, and these should never depend on an existing Python installation, if any, or interfere with it. The other part of the goal is to keep the bundle "static" after `py2exe` runtime.

> I'd like to be able to pip-install extensions to the user site directory and have that visible to the app.

I am afraid `py2exe` cannot support this as it has to be compatible with the case in which the user has no Python interpreter installed on their system. Why is it so important to have these extensions in the user site? Wouldn't it be better to just ship them in the executable bundle?

> Additionally, importing site adds several things to `__builtins__`

According to the documentation linked in your message as [1], 

> The [site](https://docs.python.org/3/library/site.html#module-site) module [...] adds several constants to the built-in namespace. They are useful for the interactive interpreter shell and should not be used in programs.

**Comment by mharbison72** [comment] 2022-10-12 16:34
> > I'd like to be able to pip-install extensions to the user site directory and have that visible to the app.
> 
> I am afraid `py2exe` cannot support this as it has to be compatible with the case in which the user has no Python interpreter installed on their system.

I don't have a system without python to test with, but wouldn't the no system python case simply mean there's no user site directory, so no modules will ever load from it?

> Why is it so important to have these extensions in the user site?

Mostly convenience.  `pip3 install --user` is a simple way to fetch most popular extensions, and that's were the installed files go.  Additionally to enable the extension, the configuration for Mercurial is a simple `extension_name=` for things on `sys.path`.  It does support `extension_name=/path/to/extension` syntax for extensions located elsewhere, but the user site path varies and it's obviously less convenient to have to figure it out and supply it.

> Wouldn't it be better to just ship them in the executable bundle?

We do bundle some, but we can't bundle everything and there's been some discussion about dialing that back.  But there'd need to be a convenient way for users to install and configure them in this case.

> > Additionally, importing site adds several things to `__builtins__`
> 
> According to the documentation linked in your message as [1],
> 
> > The [site](https://docs.python.org/3/library/site.html#module-site) module [...] adds several constants to the built-in namespace. They are useful for the interactive interpreter shell and should not be used in programs.

It was this part that motivated the issue.  Agreed that normal programs shouldn't call `exit()` or `quit()`.  But Mercurial has a debug command that calls `code.interact()`, which basically emulates the interactive shell interpreter so that you can poke at python variables, import stuff, call functions, etc.  It took me a long time to figure out why calling `quit()` to exit the shell failed in some builds but not others, and it turned out to be this.

I might be able to work around this by supplying the functions added to `__builtins__` by `site` to the `local` list passed to `code.interact()` if there are too many side effects to including `site`.

**Comment by albertosottile** [comment] 2022-10-12 16:59
I am quite confused by this issue. 

On one hand, the question can be interpreted as: can we add the `site` module to the distribution included in `py2exe` app bundles? I think my answer to this would be: we can, but it would not work, as installing  in the "app user site" is not supported by the interpreter we include in the bundle, nor by py2exe runtime. Hence, I would be against this addition.

Another interpretation is: can we **expose** the user site of an external existing Python distribution to an app frozen with py2exe? This would cover some of your use cases, but I am afraid it would be almost impossible. What distribution should the app pick (I have about a dozen of Python installations in my system...)? What if the two versions of Python (the one embedded in the app and the one in the chosen user site) are not the same? Should we also ship `pip`? `setuptools`? All this definitely exceeds the purpose of `py2exe`. For users that are willing to install a Python distribution in their system, a  wheel should be the preferred target, and not a frozen bundle.

> Mercurial has a debug command that calls code.interact(), which basically emulates the interactive shell interpreter

Well, you are running a REPL on the Python distribution frozen with `py2exe`. Honestly, I am surprised that even works... I now see why you want to support adding arbitrary packages from PyPI. I apologize if I say this a lot, but I believe that freezing a Python REPL is again, beyond the original purpose of `py2exe`. 

If, however, you still want to support this somehow, I would advise you to write a personalized copy of `site` that takes care of defining a user site for the embedded Python distribution in some internal folder of your app. Then, instruct your REPL to load this custom module when running. In this way, the embedded distribution SHOULD start picking up modules from the pointed folder. You would still not have stuff like `pip` in your distribution, though...

**Comment by mharbison72** [comment] 2022-10-12 20:04
> I am quite confused by this issue.
> On one hand, the question can be interpreted as: can we add the site module to the distribution included in py2exe app bundles?
> Another interpretation is: can we expose the user site of an external existing Python distribution to an app frozen with py2exe?

I'm suggesting adding the `site` module to the distribution, as it handles both cases.

Just for fun, I monkeypatched the build process to remove `site` from the blacklisted module list, so it would be included in the app.  Because the interpreter flags are configured with `sys.flags.no_user_site=1` and `sys.flags.no_site=1`, none of the automatic initialization is done on startup.  I didn't see any behavior change by it simply being present.  The module being present, however, makes the various functions available to the app so it can setup `builtins` and process the optional `sitecustomize` module if it chooses.  (We use this on mac with py2app to customize some paths when running in the app configuration, instead of polluting the main code.)  Manually calling `site.addusersitepackages()` does nothing, because of `no_user_site`, while `site.addsitepackages()` only adds the directory the executable lives in.  So I don't see any footguns here by calling functions on it.

> For users that are willing to install a Python distribution in their system, a wheel should be the preferred target, and not a frozen bundle.

I need a proper installer, because config files need to go into privileged locations, and a shell extension also gets installed.

> I would advise you to write a personalized copy of site that takes care of defining a user site for the embedded Python distribution in some internal folder of your app. Then, instruct your REPL to load this custom module when running.

This sounds like something the `sitecustomize` module could do.

I'm OK with closing this as a WONTFIX if you're still against simply including the module in the distribution, because there seems to be more to it than I understand, and I've got a viable workaround.  FWIW, it looks like py2app bundles a customized `site` module like you suggested that does some of the work of the real `site` module (like supplementing `buildins` and importing `sitecustomize`):

https://github.com/ronaldoussoren/py2app/blob/b28033ce670b1cdf4be4d0911433e8f55e0c28b8/src/py2app/apptemplate/lib/site.py

**Comment by albertosottile** [comment] 2022-10-12 20:51
> I'm suggesting adding the site module to the distribution, as it handles both cases.

To me it seems this can only cover the first case. I do not see how any frozen version of `site` (vanilla, patched, or custom) could find the other distributions installed in the system and allow interacting with them, especially if the frozen Python and the installed Python versions do not match. 

> Just for fun, I monkeypatched [...] while `site.addsitepackages()` only adds the directory the executable lives in. 

This makes sense, so now you have a valid user site in your custom REPL. My question now is: how can you use it? You cannot access it from outside your frozen app. Can you install packages from your REPL without a `pip` module? 

>  FWIW, it looks like py2app bundles a customized `site` module like you suggested that does some of the work of the real site module (like supplementing `builtins` and importing `sitecustomize`). (We use this on mac with py2app to customize some paths when running in the app configuration, instead of polluting the main code.)

This indeed seems a viable use case for adding this module, however a similar addition will have to be tested extensively, since `py2exe` has functioned without it for more than a decade...

> I need a proper installer, because config files need to go into privileged locations, and a shell extension also gets installed

You could still have the proper installer. My point was that you would not need to ship Python, if your users already have Python.

> I'm OK with closing this as a WONTFIX if you're still against simply including the module in the distribution

After clarification, I am not against doing this, in principle. I could see something similar to what `py2app` is doing. However, I see very little benefits from it and a lot of work/testing required. In particular, I am not convinced this covers your desired use case of "be able to pip-install extensions to the user site directory and have that visible to the app".

**Comment by mharbison72** [comment] 2022-10-13 15:39
> > I'm suggesting adding the site module to the distribution, as it handles both cases.
> 
> To me it seems this can only cover the first case. I do not see how any frozen version of `site` (vanilla, patched, or custom) could find the other distributions installed in the system and allow interacting with them, especially if the frozen Python and the installed Python versions do not match.
> 
> > Just for fun, I monkeypatched [...] while `site.addsitepackages()` only adds the directory the executable lives in.
> 
> This makes sense, so now you have a valid user site in your custom REPL. My question now is: how can you use it? You cannot access it from outside your frozen app.

You're correct that it doesn't happen automatically, but it's trivial to do `sys.path.append(site.getusersitepackages())`.  Right now I have the contents of `site.getusersitepackages()` copied into the application.

You're also correct that the 3.X versions need to match, which admittedly isn't convenient for users without the same Python version installed.  It is convenient for developers though, who can develop and test from source (using the system python) and test the frozen application with the same extensions and config file settings.

> Can you install packages from your REPL without a `pip` module?

Not right now, and I'm not sure what the plan was to handle this aspect.  The idea about a command to install extensions hasn't been discussed in awhile, and there are likely other issues with it.

> > I'm OK with closing this as a WONTFIX if you're still against simply including the module in the distribution
> 
> After clarification, I am not against doing this, in principle. I could see something similar to what `py2app` is doing. However, I see very little benefits from it and a lot of work/testing required. In particular, I am not convinced this covers your desired use case of "be able to pip-install extensions to the user site directory and have that visible to the app".

To be clear, I'm not looking for the app executable to to do this `pip` work, just be able to extend `sys.path` with the user site more easily so it can see things already installed.  Having to copy/paste this code, and missing the extra `builtins` stuff made me think I was working around too much.  The module being missing entirely (whereas PyOxidizer and py2app both have it) and the blacklist entry going back to the initial import made me think that the exclusion was a holdover from the python2 days.

I'm not sure its worth a whole lot of work either, or what sort of testing you have in mind.  I might just go the monkeypatching route to include it in my build, and let that be real world testing that I can report back.  We've got a feature release coming up in the next few weeks, so it shouldn't be long to get feedback.

**Comment by albertosottile** [comment] 2022-10-13 20:48
> You're correct that it doesn't happen automatically, but it's trivial to do `sys.path.append(site.getusersitepackages())`. Right now I have the contents of `site.getusersitepackages()` copied into the application.

> [...]  just be able to extend `sys.path` with the user site more easily so it can see things already installed.

If that's your use case, could you just use `sysconfig.get_path('purelib', os.name+'_user')` instead of `site.getusersitepackages()`? (this is what `site` actually copies in its implementation).

> I'm not sure its worth a whole lot of work either, or what sort of testing you have in mind. 

The problem is that the whole Python ecosystem is meant to work perfectly fine with the vanilla `site` module, or with no `site` module. Everything in between is absolutely not supported and can basically fail for any package on PyPI in unexpected ways. You can give a look at what can possibly go wrong In [the history of `site.py` on py2app](https://github.com/ronaldoussoren/py2app/commits/a9ee6dbb1c2a25c592ecc8e546550d17d75fd1e4/py2app/apptemplate/lib/site.py?browsing_rename_history=true&new_path=src/py2app/apptemplate/lib/site.py&original_branch=master). Honestly, I am not sure if I am willing to open that Pandora's box for the limited benefits we can foresee at the moment...

**Comment by albertosottile** [comment] 2022-10-13 20:54
>  and missing the extra `builtins` stuff 

For the missing `builtins`, since you are shipping a REPL in your app (which is a pretty peculiar need, I would say), I would advise you to follow an approach similar to what `py2app` does in https://github.com/ronaldoussoren/py2app/blob/b28033ce670b1cdf4be4d0911433e8f55e0c28b8/src/py2app/apptemplate/lib/site.py#L192-L198.

**Comment by albertosottile** [comment] 2023-05-12 17:29
I am closing this as it seems we do not have a compelling use case for this (rather cumbersome) addition. I hope the proposed approaches worked for you. Otherwise, please feel free to reopen the issue if you think you still need this feature,

**Closed by albertosottile** 2023-05-12 17:29 UTC
Labels: question
