### ISSUE TITLE
zipimport.ZipImportError: can't find module '_bz2'

### ISSUE THREAD

**Issue by 11philip22** [py2exe/py2exe#87] opened 2021-04-07 11:04 UTC
Hi,
I am getting this error when i try to run a builded exe.
```
Traceback (most recent call last):
  File "zipextimporter.pyc", line 87, in load_module
  File "<frozen zipimport>", line 241, in load_module
  File "<frozen zipimport>", line 721, in _get_module_code
zipimport.ZipImportError: can't find module '_bz2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<boot hacks>", line 17, in <module>
  File "<boot hacks>", line 3, in patch_certifi
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "zipextimporter.pyc", line 87, in load_module
  File "<frozen zipimport>", line 259, in load_module
  File "certifi\__init__.pyc", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "zipextimporter.pyc", line 87, in load_module
  File "<frozen zipimport>", line 259, in load_module
  File "certifi\core.pyc", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "zipextimporter.pyc", line 87, in load_module
  File "<frozen zipimport>", line 259, in load_module
  File "importlib\resources.pyc", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "zipextimporter.pyc", line 87, in load_module
  File "<frozen zipimport>", line 259, in load_module
  File "importlib\_common.pyc", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "zipextimporter.pyc", line 87, in load_module
  File "<frozen zipimport>", line 259, in load_module
  File "zipfile.pyc", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "zipextimporter.pyc", line 87, in load_module
  File "<frozen zipimport>", line 259, in load_module
  File "shutil.pyc", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "zipextimporter.pyc", line 87, in load_module
  File "<frozen zipimport>", line 259, in load_module
  File "bz2.pyc", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "zipextimporter.pyc", line 110, in load_module
SystemError: initialization of _bz2 did not return an extension module
Traceback (most recent call last):
  File "<frozen zipimport>", line 177, in get_data
KeyError: 'certifi\\cacert.pem'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen zipimport>", line 741, in open_resource
  File "<frozen zipimport>", line 179, in get_data
OSError: [Errno 0] : 'certifi\\cacert.pem'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "instantrip.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "zipextimporter.pyc", line 87, in load_module
  File "<frozen zipimport>", line 259, in load_module
  File "instaloader\__init__.pyc", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "zipextimporter.pyc", line 87, in load_module
  File "<frozen zipimport>", line 259, in load_module
  File "instaloader\instaloader.pyc", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "zipextimporter.pyc", line 87, in load_module
  File "<frozen zipimport>", line 259, in load_module
  File "requests\__init__.pyc", line 120, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "zipextimporter.pyc", line 87, in load_module
  File "<frozen zipimport>", line 259, in load_module
  File "requests\utils.pyc", line 40, in <module>
  File "certifi\core.pyc", line 37, in where
  File "contextlib.pyc", line 117, in __enter__
  File "importlib\resources.pyc", line 175, in _path_from_reader
  File "<frozen zipimport>", line 743, in open_resource
FileNotFoundError: certifi/cacert.pem
```
Here is my setup.py
```python
from distutils.core import setup
import sys
import py2exe

sys.argv.append('py2exe')

setup(
    options={'py2exe': {
        'bundle_files': 1, 'compressed': True,
        'packages': ['instaloader']
    }},
    console=['instantrip.py']
)
```
Could you please point out what i seem to be doing wrong?

**Comment by albertosottile** [comment] 2021-04-07 17:21
Thanks for reporting this.

It is quite hard to debug your problem without knowing the content of your package but, at first glance, I would advise you to add `certifi` to the `packages` list in your `setup.py` script, as in `'packages': ['instaloader', 'certifi']`. 

If this does not solve your issue, then I would ask you to provide a minimal code example of your script that can be used to reproduce this problem.

**Comment by 11philip22** [comment] 2021-04-08 11:59
Hi Alberto, adding certifi didnt do the trick.
Here is the build output
```
running py2exe

  28 missing Modules
  ------------------
? Cookie                              imported from requests.compat
? Queue                               imported from urllib3.util.queue
? UserDict                            imported from simplejson.ordered_dict
? _posixshmem                         imported from multiprocessing.resource_tracker, multiprocessing.shared_memory
? _testinternalcapi                   imported from test.support
? backports                           imported from urllib3.packages.ssl_match_hostname
? bcrypt                              imported from cryptography.hazmat.primitives.serialization.ssh
? brotli                              imported from urllib3.response, urllib3.util.request
? collections.Callable                imported from requests.compat, socks
? collections.Mapping                 imported from requests.compat, urllib3._collections
? collections.MutableMapping          imported from requests.compat, urllib3._collections
? cookielib                           imported from requests.compat
? cryptography.x509.UnsupportedExtension imported from urllib3.contrib.pyopenssl
? dummy_threading                     imported from requests.cookies
? readline                            imported from cmd, code, pdb
? resource                            imported from test.support
? six.moves.urllib                    imported from cryptography.hazmat.primitives.twofactor.utils
? urllib.getproxies                   imported from requests.compat
? urllib.getproxies_environment       imported from requests.compat
? urllib.proxy_bypass                 imported from requests.compat
? urllib.proxy_bypass_environment     imported from requests.compat
? urllib.quote                        imported from requests.compat
? urllib.quote_plus                   imported from requests.compat
? urllib.unquote                      imported from requests.compat
? urllib.unquote_plus                 imported from requests.compat
? urllib.urlencode                    imported from requests.compat
? win_inet_pton                       imported from socks
? win_unicode_console                 imported from instaloader
Building 'dist\instantrip.exe'.
Building shared code archive 'dist\library.zip'.
Copy DLL C:\python39\DLLs\libssl-1_1.dll to dist
Copy DLL C:\python39\DLLs\tk86t.dll to dist
Copy DLL C:\python39\DLLs\libffi-7.dll to dist
Copy DLL C:\python39\DLLs\libcrypto-1_1.dll to dist
Copy DLL C:\python39\DLLs\tcl86t.dll to dist
Copy lib file C:\python39\lib\site-packages\certifi\cacert.pem to dist
```
And i can profide the entire script im trying to build since its very small.
```python
from argparse import ArgumentParser
from urllib.parse import urlparse
from os import getcwd

from instaloader import Instaloader, Profile, Post


def main():
    parser = ArgumentParser(description='Instant Ripper')
    parser.add_argument('-u', '--username', dest='username', help='User name')
    parser.add_argument('-p', '--password', dest='password', help='password')
    parser.add_argument('-d', '--destination', dest='dest', help='Path where files are downloaded to')
    parser.add_argument('url', help='Url to page or post')
    arguments = parser.parse_args()

    if not arguments.username:
        print('[!] No username supplied')
    if not arguments.password:
        print('[!] No password supplied')
    if not arguments.username or not arguments.password:
        exit(1)
    username = arguments.username
    password = arguments.password

    if arguments.dest:
        dest = arguments.dest
    else:
        print('[*] No destination specified downloading to current working directory')
        dest = getcwd()

    url = arguments.url
    parsed_url = urlparse(url)
    if parsed_url.netloc != 'www.instagram.com':
        print(f'[!] Wrong site!\n\
        [!] Url should be: "www.instagram.com"\n\
        [!] Your url: {parsed_url.netloc}')
        exit(1)

    i = Instaloader(
        user_agent='Mozilla/5.0',
        dirname_pattern=dest + '/{profile}/{target}',
        download_video_thumbnails=False,
        download_geotags=False,
        download_comments=False,
        save_metadata=False,
        compress_json=False,
        quiet=True
    )
    i.login(username, password)

    if parsed_url.path.startswith('/p'):
        print('[*] Url is post')
        shortcode = parsed_url.path.strip('/').strip('p/')
        post = Post.from_shortcode(i.context, shortcode)

        print(f'[+] Downloading {post.url}')
        profile = Profile.from_username(i.context, post.profile)
        i.download_post(post, profile)
    else:
        profile_name = parsed_url.path.strip('/')
        print(f'[+] Ripping profile: {profile_name}')
        profile = Profile.from_username(i.context, profile_name)
        i.download_profiles(
            {profile},
            profile_pic=True,
            posts=True,
            igtv=True,
            highlights=True,
            stories=True
        )


if __name__ == '__main__':
    main()
```
Not sure where i can find the build log files. But thanks in advance

**Comment by mateiacd** [comment] 2021-04-08 23:24
I have exactly the same error with a small piece of code :
```
import requests
import json
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)


     url = 'https://xxxx.yyyyyy.io/services/json/v1'   
     headers = {'Content-Type': 'application/json;charset=utf-8'}
     command = [{"command":"SessionService.getLoginTicket","args":{"login":"SomeUser","password":"SomePassword"}}]
     inputRequest = json.dumps(command)
     response = requests.post(url, headers=headers, data=inputRequest, verify=False)
     json_data = response.json()
```

As a workaround I decided to compile this code with 'bundle_files': 3 instead of 'bundle_files': 1

**Comment by albertosottile** [comment] 2021-04-10 12:38
Generally, lower values of `bundle_files` are not supported for arbitrary packages, as I have limited capacity and introducing this extra layer of complexity leads to an unmanageable maintenance load. 

However, in this specific case, I am afraid I am unable to reproduce your error. I used the example code posted by @mateiacd and I always get the same error (`requests.exceptions.ConnectionError`) whether I use `"bundle_files": 1` or `3`. 

I would advise you both to check the content of your library zip archive and look if a `_bz2.pyd` is in there. It would also help if you could add `"verbose": 4,` in your `py2exe` dictionary, e.g. 
```python
setup(console=[{ "script": "urllib_test.py"}],
      options={"py2exe": {
            "bundle_files": 1,
            "verbose": 4,
            "packages": ['requests']}})
```
and report here the build logs. A line similar to this `Add _bz2.pyd to dist\library.zip` should be printed at build time.

**Comment by albertosottile** [comment] 2021-04-12 20:47
Ok, after three days of pain I think I got it. On Actions, you will find wheels that include the (tentative) fix for this issue https://github.com/py2exe/py2exe/actions/runs/742530743. 

If both of you could download the relevant wheel archive for your system (files on the bottom of the page), unzip it, install the wheels via pip, and confirm that you do not experience this issue anymore, that would be great. Thank you for your time.

I intend to write an explanation of this issue as a comment before closing it. If you are interested in what the fix is doing, you can give a look at the commit https://github.com/py2exe/py2exe/commit/4e5b508ad4f4e0b224927eb37f535b869e98ea3e.

**Comment by 11philip22** [comment] 2021-04-13 07:38
Hi Alberto, Thanks for swift fix! I will download and install the wheels when i get home and report back.

**Comment by mateiacd** [comment] 2021-04-13 10:35
Yes, this version py2exe-0.10.3.2-cp39-cp39-win_amd64.whl works excellent. Thank you very, very much !!
With "bundle_files": 1 the following layout is created in the dest folder and the generated executable is launched successfully!

Size            File 
(bytes)       name
------------------------
263,774      cacert.pem
3,405,504   libcrypto-1_1.dll
32,792        libffi-7.dll
689,856      libssl-1_1.dll
12,411,619 TestPython3Py2EXE.exe
4,457,136   python39.dll
1,705,120   tcl86t.dll
1,468,064   tk86t.dll

**Comment by mateiacd** [comment] 2021-04-13 11:15
The first source code snippet I posted above was just a demo, doing nothing.
Now I am adding a working example.
RestTest.py
- - - - - - - - - 
```
import sys,os

import requests
import json
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)


if __name__ == '__main__':
    
    
    url = 'https://reqbin.com/echo/post/json'
    headers =  {'Content-Type': 'application/json;charset=utf-8'}
    
    command={ "Id": 12345}
    inputRequest = json.dumps(command)
    response = requests.post(url, headers=headers, data=inputRequest,verify=False)
    json_data = response.json()
    
    print (json_data)
```
setup.py
- - - - - - - - - 
```
from distutils.core import setup
import py2exe
import sys

setup(
    options={"py2exe": {
                        'bundle_files': 1,
                        'optimize': 2,
			"verbose": 4
                       }},
    zipfile=None,
    console=[{"script":"RestTest.py"}]
    )

```

**Comment by albertosottile** [comment] 2021-04-13 17:23
@mateiacd I am glad the fix worked for you. There is no need to add a functional test code as I was able to use the code that I already have in the functional test of `requests` for this purpose. 

I will include this fix in the next release, which should occur relatively soon.

**Comment by albertosottile** [comment] 2021-04-13 17:47
As I promised, some more details about the fix, which is actually a new feature.

Python provides two ways to import and initialize extension modules: the so-called single-phase initialization (the standard way), which just calls a `PyInit_modulename` function defined in the extension code itself, and the new multi-phase initialization, defined in [PEP 489](https://www.python.org/dev/peps/pep-0489/) and introduced in Python 3.5. Essentially, the multi-phase initialization divides the process in two stages, analogue to `__new__` and `__init__` for Python classes. 

As you can imagine, `py2exe` was not compatible with multi-phase initialization, as it relied on `PyInit_modulename` to return a module ready to use. Fortunately, this limitation has more or less worked up to now, since not many extension modules have been ported to the new initialization scheme. 

Unfortunately, in Python 3.9... ([whatsnew](https://docs.python.org/dev/whatsnew/3.9.html))
> a number of Python modules (_abc, audioop, _bz2, _codecs, _contextvars, _crypt, _functools, _json, _locale, math, operator, resource, time, _weakref) now use multiphase initialization as defined by PEP 489;

which led to the issue you two reported here. `zipextimporter` was suddenly unable to import `_bz2` from the zip file as its init function did not return the module anymore (`SystemError: initialization of _bz2 did not return an extension module`). 

Given the number of standard library modules ported to the new scheme, I figured I either had to add support for PEP 489 or drop `zipextimporter` (and `bundle_files < 2`) entirely. I gave it a shot in https://github.com/py2exe/py2exe/commit/4e5b508ad4f4e0b224927eb37f535b869e98ea3e and it seems I have succeeded, though I am not an expert of the C API of Python so, some other issues could probably show up in the future. 

Anyway, thanks again for reporting this and let's hope this effort helps in keeping `py2exe` alive longer. As I said before, expect this change to be included in the next minor release.

**Comment by 11philip22** [comment] 2021-04-14 08:08
Hi with the wheels you provided my issue is fixed as well🥳 🥳 🥳 🥳

**Closed** 2021-04-14 08:11 UTC
Labels: bug

**Comment by shahzebali457** [comment] 2024-03-31 01:18
hi i am having a similar issue with PyQt5 
I tested it on both Python 3.9 and 3.11 


ImportError: MemoryLoadLibrary failed loading PyQt5\QtWidgets.pyd: The specified module could not be found. (126)
Traceback (most recent call last):
  File "zipextimporter.pyc", line 96, in load_module
  File "<frozen zipimport>", line 241, in load_module
  File "<frozen zipimport>", line 721, in _get_module_code
zipimport.ZipImportError: can't find module 'PyQt5.QtWidgets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "roof_Cost_Estimation.py", line 3, in <module>
  File "zipextimporter.pyc", line 120, in load_module
ImportError: MemoryLoadLibrary failed loading PyQt5\QtWidgets.pyd: The specified module could not be found. (126)

The error is copied from log file 



setup.py


from distutils.core import setup
import py2exe
import sys

# Add additional model files for PaddleOCR
data_files = ['paddleocr', 'yolov8upd', 'en_PP-OCRv3_det_infer', 'models']
includes=['PyQt5','pyqt5_plugins','pyqt5_tools','PyQt5.QtCore','PyQt5.QtXml', 'PyQt5.QtWidgets']
sys.argv.append('py2exe')

setup(
    options={'py2exe': {'bundle_files': 1, 'compressed': True,'includes':includes}},
    windows=[{'script': 'roof_Cost_Estimation.py'}],
    packages=data_files,
    zipfile=None,
)
