### ISSUE TITLE
exe gives No module named 'site' while using PySimpleGUI library

### ISSUE THREAD

**Issue by s-arjun** [py2exe/py2exe#115] opened 2021-11-17 18:54 UTC
Initially the py2exe couldnt find the PySimpleGUI at all whem I was trying to build it. After somehow fixing this, now this is the error that comes in the log file of the exe generated:
```
Traceback (most recent call last):
  File "gui.py", line 3, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "PySimpleGUI\__init__.pyc", line 2, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "PySimpleGUI\PySimpleGUI.pyc", line 178, in <module>
ModuleNotFoundError: No module named 'site'
```

I tried using conda as well as venv
Python version 3.9
Windows 10
py2exe 0.11.0.1 (I've also tried a few older versions, just to see if it was a bug in the latest)

This is my `setup.py`:
```
from distutils.core import setup
from setuptools import find_packages
import py2exe
import PySimpleGUI
import psgtray


setup(
    options={
        'py2exe': {
            'includes': ['PySimpleGUI', 'psgtray'],
            'packages': find_packages(),
            'bundle_files': 3,
        }
    },
    windows=[{
        'script': 'gui.py',
        'uac_info': 'requireAdministrator'
    }],
    data_files=[('data', [
        'data/params.json',
    ])]
)

```

**Comment by s-arjun** [comment] 2021-11-18 10:59
Hi... I found a workaround for this from the issue I raised in PySimpleGUI github.
I'm linking that here, just in case. 

[https://github.com/PySimpleGUI/PySimpleGUI/issues/4968](url)

**Comment by albertosottile** [comment] 2021-11-30 18:35
Hello, it is hard to me to reproduce this without a test code. However, most likely this issue occurred because you tried to freeze your app from a virtual environment (see https://github.com/py2exe/py2exe/issues/20#issuecomment-541452119), which is not supported.

Nevertheless, I see that developers of PySimpleGUI are assisting you in patching their code to avoid `import site` (which is the thing that confuses py2exe when called from a virtual environment) and other stuff. 

If you are still seeing this error without using a virtual environment, i would ask you for a simple code to reproduce this error on my side.

**Comment by albertosottile** [comment] 2021-12-18 16:40
Closing this as no input was provided up to now. Please re-open if you still manage to reproduce this error without using `conda` or `venv` as build environment.

**Closed by albertosottile** 2021-12-18 16:40 UTC
Labels: requires user input
