### ISSUE TITLE
Impossible to freeze packages with a particular layout since py2exe 0.10.2.0

### ISSUE THREAD

**Issue by lukaszgo1** [py2exe/py2exe#112] opened 2021-11-01 23:16 UTC
Originally reported as https://github.com/nvaccess/nvda/issues/12357 as this issue stops us from upgrading to post 0.10.1.0 versions of py2exe.

To reproduce try to freeze 
[py2exesample.zip](https://github.com/py2exe/py2exe/files/7456618/py2exesample.zip)
with version 0.10.1.0 and then with any later versions   including the latest 0.10.4.1. While with 10.1.0  the freezing process works as it should all  later versions provide the following error:
```
running py2exe
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    data_files=[('.', ['data.txt'])]
  File "C:\Python37\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Python37\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Python37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "D:\py2exesample\testing\lib\site-packages\py2exe\distutils_buildexe.py", line 192, in run
    self._run()
  File "D:\py2exesample\testing\lib\site-packages\py2exe\distutils_buildexe.py", line 272, in _run
    builder.analyze()
  File "D:\py2exesample\testing\lib\site-packages\py2exe\runtime.py", line 177, in analyze
    target.analyze(mf)
  File "D:\py2exesample\testing\lib\site-packages\py2exe\runtime.py", line 78, in analyze
    modulefinder.run_script(self.script)
  File "D:\py2exesample\testing\lib\site-packages\py2exe\mf34.py", line 62, in run_script
    self._scan_code(mod.__code__, mod)
  File "D:\py2exesample\testing\lib\site-packages\py2exe\mf34.py", line 386, in _scan_code
    self.safe_import_hook(name, mod, fromlist, level)
  File "D:\py2exesample\testing\lib\site-packages\py2exe\mf34.py", line 122, in safe_import_hook
    self.import_hook(name, caller, fromlist, level)
  File "D:\py2exesample\testing\lib\site-packages\py2exe\mf34.py", line 104, in import_hook
    module = self._gcd_import(name)
  File "D:\py2exesample\testing\lib\site-packages\py2exe\mf34.py", line 258, in _gcd_import
    return self._find_and_load(name)
  File "D:\py2exesample\testing\lib\site-packages\py2exe\mf34.py", line 348, in _find_and_load
    self._scan_code(module.__code__, module)
  File "D:\py2exesample\testing\lib\site-packages\py2exe\mf34.py", line 386, in _scan_code
    self.safe_import_hook(name, mod, fromlist, level)
  File "D:\py2exesample\testing\lib\site-packages\py2exe\mf34.py", line 122, in safe_import_hook
    self.import_hook(name, caller, fromlist, level)
  File "D:\py2exesample\testing\lib\site-packages\py2exe\mf34.py", line 107, in import_hook
    module = self._gcd_import(name, package, level)
  File "D:\py2exesample\testing\lib\site-packages\py2exe\mf34.py", line 258, in _gcd_import
    return self._find_and_load(name)
  File "D:\py2exesample\testing\lib\site-packages\py2exe\mf34.py", line 303, in _find_and_load
    spec = importlib.util.find_spec(name, path)
  File "C:\Python37\lib\importlib\util.py", line 94, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
  File "D:\py2exesample\samplePKG\__init__.py", line 1, in <module>
    import printData
  File "D:\py2exesample\printData.py", line 3, in <module>
    DATA_PATH = os.path.join(globalVars.appPath, globalVars.DATA_FILE_NAME)
AttributeError: module 'globalVars' has no attribute 'appPath'

```

Obviously the reproducer attached above is extremely silly and it would be easy to rewrite it, but as mentioned above we follow similar pattern in NVDA and it would be pretty difficult to modify its code so that this bug is not triggered. As soon as the line `from .functions import my_avesome_func` in `samplePKG\__init__.py` is commented out the program can be frozen successfully.

**Comment by albertosottile** [comment] 2021-11-02 18:54
Thanks for this report and the MWE, I can reproduce. Will start looking for a fix.

**Comment by albertosottile** [comment] 2021-11-02 19:10
I am not exactly sure how can I help you. First of all, the error is entirely in Python `importlib`, as it is easily visible from a quick test:
```python
Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import importlib.util
>>> importlib.util.find_spec('samplePKG.function', 'C:\\py2exe\\tests\\functional\\nvda_test\\samplePKG')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\lib\importlib\util.py", line 94, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
  File "C:\py2exe\tests\functional\nvda_test\samplePKG\__init__.py", line 1, in <module>
    import printData
  File "C:\py2exe\tests\functional\nvda_test\printData.py", line 3, in <module>
    DATA_PATH = os.path.join(globalVars.appPath, globalVars.DATA_FILE_NAME)
AttributeError: module 'globalVars' has no attribute 'appPath'
```

Second, I do not truly understand what exactly is your use case that you are not able to refactor. These are the options:
- A) a package that inside loads an internal module via `.` (`from .functions import ...`)
- B) a package that loads a module that depends on an attribute that does not exist in the code nor in the direct dependency chain

I think use case A) can be easily satisfied, so the problem most likely comes from use case B). Would it be possible for you to populate `globalVars` with the correct default values (e.g. `appPath = os.path.abspath(os.path.dirname(__file__))` and then only override when needed in `main`?

**Comment by albertosottile** [comment] 2021-11-02 19:17
As per the reasons why this code was changed in 0.10.2.0, the old module finder `mf3` was based on a lot of methods that were deprecated a long time ago. In the specific case, the line that now fails was
```python
loader = importlib.find_loader(name, path)
```
and [according to the official documentation](https://docs.python.org/3/library/importlib.html#importlib.find_loader), `find_loader` is `Deprecated since version 3.4: Use importlib.util.find_spec() instead.`

Nevertheless, `find_loader` is indeed NOT failing with your example. However, I am not sure how to help you for issues in the standard library. If you are absolutely convinced your code structure should be supported, then it might worth a shot to open a issue in the CPython tracker https://bugs.python.org/.

**Comment by lukaszgo1** [comment] 2021-11-02 20:44
> I think use case A) can be easily satisfied, so the problem most likely comes from use case B). Would it be possible for you to populate `globalVars` with the correct default values (e.g. `appPath = os.path.abspath(os.path.dirname(__file__))` and then only override when needed in `main`?


As mentioned in the initial comment this  MWE has been intentionally kept very simple, and while I can indeed add needed attributes to  `globalVars` in NVDA we're also installing `_` and `pgettext` to `globals`  to support translations and this cannot be worked around so easily.  Since during freezing these functions are not present this bug is also triggered. Just for an experiment I've created fake gettext functions before freezing and while this allowed build to continue it again fails later on this time complaining about different package and different missing attribute. I'll try to create a second MWE demonstrating this problem if needed though it is once again caused by `importlib.util.find_spec` so I\'m not sure if it will help much. Are there any real issues caused by `importlib.find_loader` or was it just replaced with `importlib.util.find_spec` since the former was deprecated?

**Comment by albertosottile** [comment] 2021-11-02 21:13
> it again fails later on this time complaining about different package and different missing attribute. I'll try to create a second MWE demonstrating this problem if needed

That looks like the same failure to me so, no need to create another MWE. 

In my view, the issue at hand here is that you have an import chain in which some attributes are loaded from a module and those attributes:
- do not exist in the code of the module
- are not overridden/defined in any other modules in the import chain under investigation

I do not see how `importlib.util.find_spec` can do its job when both these conditions are true at the same time but, I might be wrong here and that's why I suggested you to report this upstream. After all, you already have a nice MWE of this issue.

> Are there any real issues caused by importlib.find_loader or was it just replaced with importlib.util.find_spec since the former was deprecated?

`mf3` was refactored because it triggered about 10 different `DeprecationWarning` and I was afraid they were going to remove any of these methods at any point in time, effectively killing py2exe. Now the package uses `mf34`, which is essentially the same code but relying on the properly supported `importlib` API (and so, relying on spec instead of loader).

**Comment by albertosottile** [comment] 2021-11-02 21:31
A quick analysis of the[ CPython code](https://github.com/python/cpython/blob/3.9/Lib/importlib/util.py) shows this is not entirely true. The code fails on
```
        parent_name = fullname.rpartition('.')[0]
        if parent_name:
            parent = __import__(parent_name, fromlist=['__path__'])
````
in other words, it fails because we are trying to find the spec of `samplePKG.functions` and Python cannot run `import samplePKG` due to the limitations listed above. However, `printData` has the same issues, code-wise, yet `importlib.util.find_spec('printData')` works perfectly because the module has no parent, hence no import attempt is performed. 

At this point I am not so sure of what exactly the expected behavior of `find_spec` is for your MWE. I would once again encourage you to inquiry/report this upstream. Please report here the link if you choose to do so.

**Comment by albertosottile** [comment] 2021-11-02 22:38
Upon further inspection, it seems that the reference implementation of ModuleFinder works well with your code. Hence, I am probably doing something wrong in mf34, though at the moment I do not see what. I will dig further in this.

**Comment by albertosottile** [comment] 2021-11-04 22:12
I invested the last two days trying to solve this in a proper way, but I failed miserably. In the end I resorted to a dirty fix, essentially:
```python
        try:
            spec = importlib.util.find_spec(name, path)
        except (AttributeError, SyntaxError):
            # spec detection method used in ModuleFinder
        except further exceptions that were there before...
```
I tried to replace the `find_spec` method to use only the one used in ModuleFinder, I tried to replace `mf34` with a new finder based on ModuleFinder, I tried to refactor `mf34` to use the `_find_spec` function from ModuleFinder.... in a nutshell, I tried to do this in a clean way but I always got a different failure somewhere (API tests, synthetic tests, functional tests).

Believe it or not, this is the ONLY solution I could find that would still allow the CI/CD pipeline to pass (the current status) AND run with your MWE. As you can see though the except clause is quite generic and stupid so, I hope it covers your real use case as well (and I hope it does not break other people work, though that's less likely).

You can download preliminary wheels with this fix from here: https://github.com/py2exe/py2exe/actions/runs/1423373463 . Please let me know if you are able to build NVDA with these wheels and, if not, report the error here.

**Comment by lukaszgo1** [comment] 2021-11-04 22:40
@albertosottile  Many thanks for you work here! In addition to catching `(AttributeError, SyntaxError)` I had to catch also `NameError` as we insert `pgettext` to `builtins` and since we have some translatable strings at the module level freezing process was failing. Aside from this there is one additional problem but it is due to a bug in one of our dependencies comtypes and I'm pretty confident I will be able to work around this on  NVDA's side. Long story short if you would also start catching `NameError` I believe it should be possible to freeze NVDA with the latest version of py2exe.

**Comment by albertosottile** [comment] 2021-11-09 19:10
@lukaszgo1 Hey, sorry for the long wait but I was not satisfied at all with the "solution" I proposed above, so I pursued further reimplementing the module finder on top of `modulefinder.ModuleFinder`, which I did in the `mf310` branch. 

Could you download the relevant wheels from here: https://github.com/py2exe/py2exe/actions/runs/1440911017 and try again in freezing NVDA with those? Thank you for your assistance.

**Comment by lukaszgo1** [comment] 2021-11-09 21:04
I can confirm that with the wheels to which you've linked above NVDA can be frozen correctly, and the resulting binary works as expected. May I ask if you have any ETA for a official release with this fix? Many thanks for your work!

**Comment by albertosottile** [comment] 2021-11-09 21:28
> May I ask if you have any ETA for a official release with this fix?

You are asking a very good question here... Because this is a complete rewrite of a critical component of `py2exe`, it is very likely it will cause issues to users. Hence I would:
- **1)** signal this with a "major" version number bump -> `0.11.x`
- **2)** perform a few "real world" tests (e.g. freezing of complex software) before deploying this

Because of **1)**, I would first release `0.10.5.0` with support for Python 3.10 and some minor bugfixes, which has been ready for a while (only full CI is missing on 3.10 because of missing wheels from tested packages). 

**2)** also takes a while to freeze and verify the frozen software. 

Hence, realistically I would say end of the month for an "official" release? Otherwise, if this could be useful for you, I could deploy on PyPI a prerelease tag, e.g `0.11.0.0b1`, but you would have to pass `--pre` to `pip install` to install it.

**Comment by lukaszgo1** [comment] 2021-11-10 14:30
> Hence, realistically I would say end of the month for an "official" release? 


This is fine for me.

> Otherwise, if this could be useful for you, I could deploy on PyPI a prerelease tag, e.g `0.11.0.0b1`, but you would have to pass `--pre` to `pip install` to install it.


Thanks for your proposal, but since the official release is not as far as I feared it would be it is unlikely NVDA would migrate to a prerelease version just to move to an official release after a few weeks  plus adding support for installation of prerelase packages to our build  system is not worth the effort.

**Comment by albertosottile** [comment] 2021-11-14 11:21
My original plan was derailed by the fact that the candidate minor `0.10.5.0` stopped passing the `scipy` test with their new release. The error would have required fixes on `mf34` which, as you can imagine, did not really make sense anymore. Hence I aborted the idea of releasing a minor and went directly into releasing `0.11.0.0`, which uses the new module finder `mf310`, fixes this issue, and should be out on PyPI by now. 

So, I am closing this issue. Please report if you have other problems in packaging NVDA with `0.11.0.0`.

**Closed by albertosottile** 2021-11-14 11:21 UTC
Labels: bug
